#!/bin/sh

#based on https://github.com/ericmurphyxyz/dotfiles/blob/master/.local/bin/battery-alert

# Send a notification if the laptop battery is either low or is fully charged.
# Set on a systemd timer (~/.config/systemd/user/battery-alert.timer).

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

# Battery percentage at which to notify
WARNING_LEVEL=15
CRITICAL_LEVEL=5
BATTERY_DISCHARGING=$(acpi -b | grep "Battery 0" | grep -c "Discharging")
BATTERY_LEVEL=$(acpi -b | grep "Battery 0" | grep -P -o '[0-9]+(?=%)')

battery-caution-symbolic
# Use files to store whether we've shown a notification or not (to prevent multiple notifications)
FULL_FILE=/tmp/batteryfull
CRITICAL_FILE=/tmp/batterycritical
battery-caution-symbolic

# Reset notifications if the computer is charging/discharging
if [ "$BATTERY_DISCHARGING" -eq 1 ] && [ -f $FULL_FILE ]; then
  rm $FULL_FILE
fi

# If the battery is charging and is full (and has not shown notification yet)
if [ "$BATTERY_LEVEL" -gt 99 ] && [ "$BATTERY_DISCHARGING" -eq 0 ] && [ ! -f $FULL_FILE ]; then
  notify-send "Battery Charged" "Battery is fully charged." -i "./battery-charged.png" -r 9991
  touch $FULL_FILE
  # If the battery is low and is not charging (and has not shown notification yet)
elif [ "$BATTERY_LEVEL" -le $WARNING_LEVEL ] && [ "$BATTERY_DISCHARGING" -eq 1 ]; then
  notify-send "Low Battery" "${BATTERY_LEVEL}% of battery remaining." -u critical -i "/usr/share/icons/Adwaita/symbolic/status/battery-caution-symbolic.svg" -r 9991
  # If the battery is critical and is not charging (and has not shown notification yet)
elif [ "$BATTERY_LEVEL" -le $CRITICAL_LEVEL ] && [ "$BATTERY_DISCHARGING" -eq 1 ] && [ ! -f $CRITICAL_FILE ]; then
  notify-send "Battery Critical" "The computer will shutdown soon." -u critical -i "/usr/share/icons/Adwaita/symbolic/status/battery-level-0-symbolic.svg" -r 9991
  touch $CRITICAL_FILE
fi
